org.gradle.caching=true
group=io.ballerina.lib

# This is a dummy value as repo contains multiple packages
version=1.0.0-SNAPSHOT
api_outbound_delivery_srv_0002Version=1.0.0-SNAPSHOT
api_inbound_delivery_srv_0002Version=1.0.0-SNAPSHOT
api_customer_returns_delivery_srv_0002Version=1.0.0-SNAPSHOT
api_del_doc_with_credit_blockVersion=1.0.0-SNAPSHOT

ballerinaGradlePluginVersion=4.0.1
downloadPluginVersion=5.4.0
releasePluginVersion=3.1.0

ballerinaLangVersion=2201.9.0
