[package]
org = "ballerinax"
name = "@package.name@"
version = "@toml.version@"
distribution = "2201.9.0"
authors = ["Ballerina"]
keywords = ["Business Management/ERP", "Cost/Paid", "Vendor/SAP", "Sales and Distribution", "SD"]
export = ["@package.name@"]
repository = "https://github.com/ballerina-platform/module-ballerinax-sap.s4hana.delivery"
icon = "../icon.png"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
