[package]
org = "ballerinax"
name = "sap.s4hana.api_del_doc_with_credit_block"
version = "1.0.0"
distribution = "2201.9.0"
authors = ["Ballerina"]
keywords = ["Business Management/ERP", "Cost/Paid", "Vendor/SAP", "Sales and Distribution", "SD"]
export = ["sap.s4hana.api_del_doc_with_credit_block"]
repository = "https://github.com/ballerina-platform/module-ballerinax-sap.s4hana.delivery"
icon = "../icon.png"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
